### ISSUE TITLE
Your code is very good, but there will be a lot of white delays before the fire. How to detect this?

### ISSUE THREAD

**Issue by Cuiys1458** [tobybreckon/fire-detection-cnn#10]
**Describe the issue**
< insert a clear and concise description of what the issue is >.

**Computing Environment (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.... LTS ]
 - Tensorflow Version:  [e.g. 1.x]
 - OpenCV Version: [e.g. 3.4.x]

**Additional context**

**Comment by tobybreckon** [comment]
I am sorry I don't understand what you mean by 'white delays'…? Do you mean smoke?

Please provide a link or upload a video file (e.g. YouTube) that illustrates the problem.

**Comment by tobybreckon** [comment]
closed, no response
