### ISSUE TITLE
Question about use of LRN

### ISSUE THREAD

**Issue by emezh** [tobybreckon/fire-detection-cnn#14]
Thank you for publishing the fire detection CNN.

Could you pls comment how important is LRN to achieve the accuracy claimed in your paper? (Perhaps you have tried a variant of a network without LRN).
Original AlexNet paper claimed that dropping LRN decreased accuracy by few percentage points - but that was for the ImageNet set with 1000 classes.

Thanks

**Comment by tobybreckon** [comment]
A good question. My co-author @AndyDunnings maybe able to answer this one but as far as I am aware we did not explore the impact of Local Response Normalization (LRN). My feeling is it would have less impact on a binary problem like this - but the only way to know is to test it. Future work ... or something for someone to try out using our published dataset in an ablation study on FireNet (not included in our 4-page ICIP paper).
