### ISSUE TITLE
Value Error when loading .pb

### ISSUE THREAD

**Issue by InduManimaran** [tobybreckon/fire-detection-cnn#17]
I am trying to load firenet.pb into a graph using the following code:
```
with tf.gfile.GFile("./converter/firenet.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph = tf.import_graph_def(graph_def,name="",input_map=None)
```
It raises the following ValueError:
```
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node Dropout_1/cond/dropout/random_uniform/max_1}}
```
I realize that I need to set the input_map to {'Const': tensor}
Could someone help to determine the tensor object ?

**Comment by tobybreckon** [comment]
I am not sure I fully understand what you want to achieve but perhaps look at the code in: [https://github.com/tobybreckon/fire-detection-cnn/blob/master/converter/converter.py](https://github.com/tobybreckon/fire-detection-cnn/blob/master/converter/converter.py)

lines 78-82 - where this is done based on the network loaded from the TFLearn format (before conversion to protocol buffer).

**Comment by InduManimaran** [comment]
Thank you. That is helpful.
