### ISSUE TITLE
Training supplement

### ISSUE THREAD

**Issue by Jayzzc** [tobybreckon/fire-detection-cnn#18]
Can I upload a training program?

**Comment by tobybreckon** [comment]
Yes - submit it as a pull request, although my aims are to keep the code base well documented, easy to maintain and not reliant on any additional dependencies (packages) than it does already.

If it meets these criteria and follows the coding/documentation style consistent with the current repo code I am happy to consider it.

**Comment by Jayzzc** [comment]
Sorry, I made a mistake. I want the training code of the program.Can you provide it?

**Comment by tobybreckon** [comment]
Sorry - only the inference code is provided, in order to make it easier to maintain.

These are very standard models (based on AlexNet and InceptionV1/GoogleNet) - any standard training tutorial in any of the major frameworks will allow you to train them, via transfer learning or otherwise.
