### ISSUE TITLE
predict problem

### ISSUE THREAD

**Issue by Jayzzc** [tobybreckon/fire-detection-cnn#19]
Can I put the picture in the code for monitoring the video?
 I am not sure if generating a pb file is helpful for image monitoring.

**Comment by tobybreckon** [comment]
If you mean - how do I load an image into python and process it with this CNN model ?

See the set of tutorials for OpenCV - https://docs.opencv.org/4.1.0/d6/d00/tutorial_py_root.html

Also see the example in the test script for the convertor which does this with the .pb file, loading a jpg image from file: https://github.com/tobybreckon/fire-detection-cnn/blob/master/converter/test-pb-opencv.py 

If you need to process multiple images, combine the former example with code like this:
https://github.com/tobybreckon/python-examples-cv/blob/master/cycleimages.py

[This assumes you have a working knowledge of OpenCV and Python - if you do not, folllow the appropriate tutorials first before posting further queries]
