### ISSUE TITLE
Firenet not able to open

### ISSUE THREAD

**Issue by sommeralex** [tobybreckon/fire-detection-cnn#2]
Hi! 

I am trying to open firenet, 

`model = construct_firenet (224, 224)`
`model.load("C:/FireNet",weights_only=True)`

but i keep getting this error: 

INFO:tensorflow:Restoring parameters from C:/FireNet

---------------------------------------------------------------------------
DataLossError                             Traceback (most recent call last)
~\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

DataLossError: Unable to open table file C:\FireNet: Unknown: NewRandomAccessFile failed to Create/Open: C:\FireNet : Access is denied.
; Input/output error
	 [[{{node save_34/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/ta`

**Comment by tobybreckon** [comment]
This appears to be a file access error on MS Windows related to access permissions or availability of the files. Check you have successfully downloaded the models files from the link/script provided and placed them in the location referenced for model loading by the provided python code.

Ultimately, the provided software is fully tested and supported for Linux only.
