### ISSUE TITLE
Predictive effect problem

### ISSUE THREAD

**Issue by Jayzzc** [tobybreckon/fire-detection-cnn#20]
Hello, sir, since your training picture is 224*224 pixels, but I tested 100*100 and 1000*1000, I found that the effect is not good. 
Why is this?
And I have adjusted the size using the cv2.resize() function before the prediction.
I also want to know how big the size of the pictures you train.
Thank you professor！

**Comment by tobybreckon** [comment]
Run your image with this example (editing line 35) - https://github.com/tobybreckon/fire-detection-cnn/blob/master/converter/test-pb-opencv.py - removing the cropping line 36. What result do you get ?

+ post a link to your example image

The model is 93 accuracy, not 100% accuracy - as per the paper.
The sizes of the training images vary and are available in the data set - download it.

**Comment by Jayzzc** [comment]
I would also like to ask you how many pictures you have trained and how many rounds you have trained to achieve this effect.

**Comment by tobybreckon** [comment]
As per the information in the paper and also in the README with the dataset.

We trained for 150 epochs.

**Comment by Jayzzc** [comment]
Sir, I am in Asia, I can't access the dataset link. 
Do you have any other link support?

**Comment by tobybreckon** [comment]
No sorry - I am reliably informed the dataset link works globally, unless it is blocked at your end.

I am unable to offer an alternative download location due to its size.
