### ISSUE TITLE
TFLite model conversion

### ISSUE THREAD

**Issue by ashwin-phadke** [tobybreckon/fire-detection-cnn#21]
**Describe the bug**
 After converting the model to .pb file using firenet-to-protobuf I am trying to convert it to TFlite model for inferencing on Google Coral USB accelerator, however while using tflite_convert command line to do so I am encountering the error as mentioned below in the output section and there is no resolution as of yet, is it the dropout layer which is the issue? 

**To Reproduce: (please complete the following information):**

1. Convert model to pb file using firenet-to-protobuf.py file.
2. Run tensorflow lite conversion command as 'tflit_convert --graph_def_file='path_to_filr/firenet.pb  --output_format=TFLITE --output_file=firenet_v1__new.tflite  --input_arrays=input --output_arrays=final_result''

**Error output received**

```
pi@raspberrypi:~ $ tflite_convert --graph_def_file=/home/pi/Downloads/FireDetection/code/firenet.pb --output_format=TFLITE --output_file=firenet_v1__new.tflite  --input_arrays=input --output_arrays=final_result
WARNING: Logging before flag parsing goes to stderr.
W0729 04:04:35.524526 3069684432 deprecation_wrapper.py:118] From /usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py:98: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0729 04:04:35.525118 3069684432 deprecation_wrapper.py:118] From /usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py:98: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

W0729 04:04:35.525362 3069684432 deprecation_wrapper.py:118] From /usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py:98: The name tf.COMPILER_VERSION is deprecated. Please use tf.version.COMPILER_VERSION instead.

W0729 04:04:35.525576 3069684432 deprecation_wrapper.py:118] From /usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py:98: The name tf.CXX11_ABI_FLAG is deprecated. Please use tf.sysconfig.CXX11_ABI_FLAG instead.

W0729 04:04:35.525793 3069684432 deprecation_wrapper.py:118] From /usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py:98: The name tf.ConditionalAccumulator is deprecated. Please use tf.compat.v1.ConditionalAccumulator instead.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 428, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node Dropout_1/cond/dropout/random_uniform/max}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 124, in _convert_tf1_model
    converter = _get_toco_converter(flags)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 111, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/python/lite.py", line 633, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 432, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node Dropout_1/cond/dropout/random_uniform/max}}
```

**Computing Environment (please complete the following information):**
 - OS: Raspbian Buster
 - Tensorflow Version:  1.13.1
 - OpenCV Version: 3.2.0
 
 

**Additional context**

**Comment by tobybreckon** [comment]
Thanks for the bug report, please appreciate tflite is beyond the immediate scope of the repo provided here but I will do my best to help ... 

I am unfamiliar with tflite_convert ... but should the arguments "--input_arrays=input --output_arrays=final_result" perhaps refer to layer labels already present in the model being converted ? (e.g. be the same as my specification in  firenet-to-protobuf.py, lines 33/34 ...

```
input_layer_name = 'InputData/X'                  # input layer of network
output_layer_name= 'FullyConnected_2/Softmax' # output layer of network
```

making ... 

```
tflite_convert ...  --input_arrays=InputData/X --output_arrays='FullyConnected_2/Softmax
```

) - this is just a guess. 

Alternatively, comment out dropout layers in: https://github.com/tobybreckon/fire-detection-cnn/blob/master/firenet.py (lines 48 / 51) and then rerun the conversion to .pb using firenet-to-protobuf.py script ... then retry your tflite conversion. 

I think you may need both of the above steps possibly.

Please post back to let me know your mileage with the above.

**Comment by tobybreckon** [comment]
Reading here - [https://www.tensorflow.org/lite/convert/cmdline_examples](https://www.tensorflow.org/lite/convert/cmdline_examples) - it appears I may be correct on the command line arguments front.

**Comment by ashwin-phadke** [comment]
Agreed, I am training by commenting the dropout layers. However, my concern being , if we remove the dropout won't it affect accuracy to a certain extent as there is nothing preventing overfitting or correction I suppose?

**Comment by ashwin-phadke** [comment]
Post providing input shape I encountered a bizarre error as 
```
ImportError: /usr/local/lib/python3.7/dist-packages/tensorflow_core/lite/toco/python/_tensorflow_wrap_toco.so: undefined symbol: _ZN6tflite12tensor_utils27NeonSymmetricQuantizeFloatsEPKfiPaPfS4_S4_
```

Looking solutions for which leads me to position wherein I need to build and install tensorflow from source.
What can be done here alternatively?

**Comment by tobybreckon** [comment]
Do you mean "training" with the dropout layers commented out or runtime test/inference using the pre-trained model ?

I ask, as this repo doesn't provide code to do the training part itself.

On my todo list is as follows:
1. change the lines 48/51 in firenet.py to be similarly inside an if statement for the `training` boolean flag with `construct_firenet()`
2. test runtime test/inference with and without the `training` flag set over the first N frames of the sample mp4 video provided with the models to see if the output differs
3. possibly wrap this test into a python unit test framework specific to this repo 
[https://docs.python.org/3/library/unittest.html](https://docs.python.org/3/library/unittest.html)

re: Edit 2 - sorry you are at the end of my tflite_convert knowledge.

**Comment by tobybreckon** [comment]
re: ImportError post 

Sorry - this is beyond my immediate knowledge base for solving this specific issue but appears to be a library dependency issue, I agree.

**Comment by ashwin-phadke** [comment]
> Do you mean "training" with the dropout layers commented out or runtime test/inference using the pre-trained model ?
> 
Yes

> I ask, as this repo doesn't provide code to do the training part itself.
> 
> On my todo list is as follows:
> 
> 1. change the lines 48/51 in firenet.py to be similarly inside an if statement for the `training` boolean flag within the `construct_firenet()` routine (and similarly for other 2 models in repo)
> 2. test runtime test/inference with and without the `training` flag set over the first N frames of the sample mp4 video provided with the models to see if the output differs
> 3. possibly wrap this test into a python unit test framework specific to this repo
>    https://docs.python.org/3/library/unittest.html
> 
That is really great to know, how can I help?
> re: Edit 2 - sorry you are at the end of my tflite_convert knowledge.
It's okay , I figured it out.
The solution is to build tensorflow from source along with bazel with Neon instructions enabled in the flag.
