### ISSUE TITLE
it takes forever downloading the training data from the given url

### ISSUE THREAD

**Issue by tenggyut** [tobybreckon/fire-detection-cnn#23]
It seems not possible to download the dataset from the given url. The download speed is around 30kb/s and the connection is also not stable.....

any plans to upload the dataset and pretrain model to other popular cloud storages?

**Comment by tobybreckon** [comment]
There appears to be an issue with the server presently. 

![image](https://user-images.githubusercontent.com/3429179/62857363-56bddd80-bcef-11e9-984a-767061cd866c.png)

I have raised a ticket with our support team

Sorry - this is going to be its permanent location now.

**Comment by tenggyut** [comment]
what's your typical download speed from this site?  does this site have a download speed limit? Currently my downloading is still going on, but the speed makes me very depressing, around 50kb/s

**Comment by tobybreckon** [comment]
I have just tested from a machine hosted in the US (Utah) - I get 400kb/s.
... from a machine hosted elsewhere in the UK (Edinburgh) I get 5Mb/s (I am in the UK also - but in Durham). Locally, I get a transfer speed of ~10Mb/s.

I conclude the slow speeds you see are not a bottle-neck from our network but beyond it.

**Comment by tenggyut** [comment]
Just like I am afraid of.....I will figure out some workaround.
Thanks
