### ISSUE TITLE
Model and Data script file is not working. Could you please help me with that.

### ISSUE THREAD

**Issue by Subhraj07** [tobybreckon/fire-detection-cnn#24]
**Describe the issue or your query**
Insert a clear and concise description of what the issue is.

**Computing Environment (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.... LTS ]
 - Tensorflow Version:  [e.g. 1.x]
 - OpenCV Version: [e.g. 3.4.x]
 
 - alternative machine learning environment / toolkit (if applicable): [e.g. keras, pytorch + version]

**Additional context**

**Comment by tobybreckon** [comment]
You have provided none of the requested information asked for and instead leaving the defaults and put the query in the subject  line ?!?  

Please repost your issue with all of the requested information filled in, then I can try and help you.

**Comment by tobybreckon** [comment]
No update or information received - closing

**Comment by Subhraj07** [comment]
Hi,

Sorry for delay in response.

Could you please help me with the script which can download the datasets as well as model As current script is not working.

Regards,
jit

**Comment by tobybreckon** [comment]
Yes - please provide the set of details set out in the bug report template and also the error message it produces.

**Comment by Subhraj07** [comment]
> Yes - please provide the set of details set out in the bug report template and also the error message it produces.

It is working now. It has some issues yesterday. Thanks for your help.
