### ISSUE TITLE
Model/Dataset Download Issues ..

### ISSUE THREAD

**Issue by tobybreckon** [tobybreckon/fire-detection-cnn#25]
If you are having any issues with the download of the network models or datasets, first manually check the availability (and/or speed) of access to [https://collections.durham.ac.uk](https://collections.durham.ac.uk) where both are hosted before posting an issue - occasionally due to network maintenance or similar the server may be temporarily unavailable; if so try again in +12-24 hours.

Speeds tested as 5Mb/s (UK), 400Kb/s (US), 10Mb/s (locally, Durham University).

Provided download scripts tested and supported on Linux (only). Direct download URL are provided in [README](https://github.com/tobybreckon/fire-detection-cnn/).

**Known issue (late Sept. 2019, now fixed):**  the file on the server may be moved to a cache due to popularity of the download. The server issues an http redirect but the scripts (prior to recent update) did not follow these http directive. Now fixed with the addition of ``-L`` to the curl command in the download script. Solution: ``git pull`` to get latest version of the repo, then retry download script command - see [README](https://github.com/tobybreckon/fire-detection-cnn/). If using the direct URL specified, make sure your download tool also follows http redirect directives (most browsers do this automatically).

**Comment by lchunleo** [comment]
hi 

 i am trying to download the model but it seems to take very long. is there some ways i can download like from a google drive ? thank you

**Comment by tobybreckon** [comment]
No sorry - they are hosted on long-term archive storage locally at Durham.
