### ISSUE TITLE
downloading models get "md5sum: WARNING: 1 computed checksum did NOT match"

### ISSUE THREAD

**Issue by Maxwills1983** [tobybreckon/fire-detection-cnn#27]
**Describe the bug**

when l run download-models.sh 

Downloading pretrained models...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   165    0   165    0     0     11      0 --:--:--  0:00:14 --:--:--    39
checking the MD5 checksum for downloaded models...
dunnings-2018-fire-detection-pretrained-models.zip: fail
md5sum: WARNING: 1 computed checksum did NOT match

**Comment by tobybreckon** [comment]
Thanks for reporting this (sorry for delayed response, I was on vacation).

Problem: the files moved on the server, the script didn't follow the automatic server redirect it appears.
Solution: add -L option to curl command in download scripts 

Not tested as working as far as I can tell. Can you confirm ?

**Comment by Maxwills1983** [comment]
when i run the latest script,get below error

root@dlxx-Alienware-15-R3:~/fire-detection-cnn# python download-models.sh
  File "download-models.sh", line 7
    URL_MODELS=https://collections.durham.ac.uk/downloads/r19880vq98m
                    ^
SyntaxError: invalid syntax
root@dlxx-Alienware-15-R3:~/fire-detection-cnn#

**Comment by tobybreckon** [comment]
Command is:

```sh ./download-models.sh```

as it's not a python script. Easily done.
