### ISSUE TITLE
Could you please tell me how to train my own model with pretrained models ?

### ISSUE THREAD

**Issue by yelingyunlmm** [tobybreckon/fire-detection-cnn#29]
**Describe the issue or your query**
Insert a clear and concise description of what the issue is including any steps to reproduce and/or relevant script output.

**Computing Environment (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.... LTS ]
 - Tensorflow Version:  [e.g. 1.x]
 - OpenCV Version: [e.g. 3.4.x]
 
 - alternative machine learning environment / toolkit (if applicable): [e.g. keras, pytorch + version]

**Additional context**

**Comment by yelingyunlmm** [comment]
Before,  I am used to training my model based on models given by tensorflow API. Since there is no config file you give I can modify, so I was confused. Looking forward to your reply. Thanks!

**Comment by tobybreckon** [comment]
This repository does not use tensorflow but tflearn. As per the FAQ training code is not provided.

If you wish to train your own model - follow a tutorial in <insert name of your deep learning environment of choice> on how to (a) define your own custom model architecture) and (b) train a model from using a custom dataset. Subsequently, use this knowledge to define a model architecture matching those described in our code/paper/diagrams and also to train from our fire dataset that you have downloaded (see README.txt file within the datset download for details on which images to train on).
