### ISSUE TITLE
I can't download pretrain models in collections.durham  

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [tobybreckon/fire-detection-cnn#32]
Hi @tobybreckon  
I run SH file but when I checking the server web is death. You can public a pre-trained model in another place or you can fix this website?

Thank you for reading my issue. I hope I can receive  your response 

Thai Hoc

**Comment by tobybreckon** [comment]
The server collections.durham.ac.uk is currently down, giving an error page via http. 

This has been reported to the support team managing this server. As it is Sunday today (UK, 3pm), it is likely to be Monday before this resource is available for download again at the earliest (9am onwards, UK time).

I will keep you updated.

**Comment by NguyenThaiHoc1** [comment]
Thank Professor for supported

**Comment by NguyenThaiHoc1** [comment]
Hi Professor @tobybreckon  you can public model on another place ? because I'm very need to your model and The website is still currently down. 
Thank Professor so much ! 
Thai Hoc

**Comment by tobybreckon** [comment]
The server is back on-line and the download scripts are working.
