### ISSUE TITLE
How to detect a fire on the image ?

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [tobybreckon/fire-detection-cnn#33]
Hi everyone
I see file superpixel-inceptionV10Fire.py and I knew it which detect fire. But I would like to expand the issue because All calculator executes on the image which using CPU and I very confuse when I knew it

I have a question? How do I detect fire on the image (a type of Bounding box ???)

Thank for reading 
Thai Hoc

**Comment by tobybreckon** [comment]
> I see file superpixel-inceptionV10Fire.py and I knew it which detect fire. But I would like to expand the issue because All calculator executes on the image which using CPU and I very confuse when I knew it

The network runs on the GPU presently for classification. If you which to also perform the superpixels part on a GPU, I would suggest using GSLIC for this part instead - https://github.com/carlren/gSLICr or similar.

> I have a question? How do I detect fire on the image (a type of Bounding box ???)

This network does not perform that by default - but the superpixels approach can do this by combining it with the Douglas-Pecker contour algorithm and taking the min/max bounds of the contour - see the pinned PAQ issue post for details.

For more details of what the code does - please read the accompanying research paper.

**Comment by NguyenThaiHoc1** [comment]
Thank professor for response !
