### ISSUE TITLE
The download training set is inconsistent to paper description

### ISSUE THREAD

**Issue by hliu2016** [tobybreckon/fire-detection-cnn#4]
Hi, I have downloaded the training set from the link you provide. The training set includes 6642 fire images and 8456 nofire images. However, they are smaller than the training set for full-frame binary fire detection problem described in your publication. Could you tell me where I can download other images? Thanks a lot.

**Comment by lizirui287** [comment]
Hello, I can't get the flame dataset from the link you gave. Is the display empty?thank you very much

**Comment by lizirui287** [comment]
> 嗨，我已从您提供的链接下载了培训集。训练集包括6642个火图像和8456个nofire图像。但是，它们小于您的出版物中描述的全帧二进制火灾探测问题的训练集。你能告诉我在哪里可以下载其他图片吗？非常感谢。

你好，原链接不用下载了。您能把下载的数据集分享一份给我吗？

**Comment by lizirui287** [comment]
> Hi, I have downloaded the training set from the link you provide. The training set includes 6642 fire images and 8456 nofire images. However, they are smaller than the training set for full-frame binary fire detection problem described in your publication. Could you tell me where I can download other images? Thanks a lot.

Hello, the original link does not need to be downloaded. Can you share a copy of the downloaded data set with me?

**Comment by tobybreckon** [comment]
Sorry for the delay on fixing this. 

Please download the full dataset from https://durhamuniversity.box.com/s/bxp9bvfcz3anb3lk2f4f3z3rtqyug5b1

This is a temporary solution. No login required, we have updated the record at: https://collections.durham.ac.uk/files/r2d217qp536#.XH0m3JzgrOG to say "Please download this dataset from DU Box as follows:  https://durhamuniversity.box.com/s/bxp9bvfcz3anb3lk2f4f3z3rtqyug5b1 Note: Login is *not* required." 

This dataset contains all of the images we used for the work including the full images and the superpixels images. It is 10.5Gb.

**Comment by hliu2016** [comment]
@tobybreckon 
Hi, the link of DU Box can not be opened. Is there any other link to get the full training dataset? Thanks a lot.

**Comment by tobybreckon** [comment]
Just tested this from firefox, link works for me.
