### ISSUE TITLE
Labeling the fire in real-time

### ISSUE THREAD

**Issue by AlaaSerhal** [tobybreckon/fire-detection-cnn#41]
Thank you so much for the great contribution. I'm working on a smart fire fighting sprinkler that would direct water exactly to the burning area after the detection of fire and I'm using raspberry pi for the processing of the frames. I was wondering if this project can be further edited to have a a bounding box or a contour surrounding the exact location of fire in the frames detected in real-time, not exactly as the output of the "superpixel-inceptionV1OnFire.py". Any suggestions or pieces of advice is appreciated.

**Comment by tobybreckon** [comment]
Yes - this can be done based on using the superpixel code and taking the min/max x/y of the detected superpixels in the scene. The superpixel code will be slow on a RPi, however so will any R-CNN/Yolo/SSD based region detection approach.
