### ISSUE TITLE
Tensor flow 2.0 compatibility issue 

### ISSUE THREAD

**Issue by netrosec** [tobybreckon/fire-detection-cnn#44]
I'm running tensorflow 2.0 and it throws this error `ModuleNotFoundError: No module named 'tensorflow.contrib'` when i run the firnet.py. Now I understand that `tf.contrib` does not exist on tensorflow 2.0. I don't' want to have to downgrade, what can i do?

**Computing Environment (please complete the following information):**
 - OS: [Ubuntu 19.10]
 - Tensorflow Version:  [2.0]
 - OpenCV Version: [4.0.0]

**Comment by tobybreckon** [comment]
I unfortunately don't have the time to look into this in depth now, but essentially the code needs to be migrated to Tensorflow V2 - https://www.tensorflow.org/guide/migrate

Alternatively run Tensorflow v1.x through a virtual environment.

**Comment by netrosec** [comment]
I installed tensorflow 1.3 on a virtual environment and it worked out the box. Saves anybody the stress of porting code.

**Comment by tobybreckon** [comment]
Excellent, glad to know it worked - thanks for letting me know.
