### ISSUE TITLE
Network Architecture 

### ISSUE THREAD

**Issue by lyokelin** [tobybreckon/fire-detection-cnn#5]
@tobybreckon Hi! Is it possible to seek some clarification on your deep learning network architecture! Thank you so much. Looking forward to hear from you!

**Comment by tobybreckon** [comment]
.. from the four page paper, diagrams and full source code provided - which part is not clear?

**Comment by lyokelin** [comment]
Hi,
Thank you so much for the reply! Currently I’m a student researching on fire-detection program and happen to come across your work. Is it possible to explain the figure as shown below! Thank you so much!
[cid:image003.png@01D4D8FB.F79D9E80]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tobybreckon** [comment]
Please read the paper PDF, then read the references from the paper - if you need background please refer to http://www.deeplearningbook.org/
