### ISSUE TITLE
Cannot download the datasets or the pretrained models

### ISSUE THREAD

**Issue by chauthehan** [tobybreckon/fire-detection-cnn#50]
**Describe the issue or your query**
Insert a clear and concise description of what the issue is including any steps to reproduce and/or relevant script output.

**Computing Environment (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.... LTS ]
 - Tensorflow Version:  [e.g. 1.x]
 - OpenCV Version: [e.g. 3.4.x]
 
 - alternative machine learning environment / toolkit (if applicable): [e.g. keras, pytorch + version]

**Additional context**

**Comment by tobybreckon** [comment]
Strange as it may seem .. I would need more details to resolve this for you such as a copy of the error message you receive and details filled in of the issue form template provided ... + also see the pinned issue on this first.

I have just tested the scripts from off-site (at Wed 13 May 12:14:29 BST 2020):
```
sh ./download-dataset.sh
...
sh ./download-models.sh
```

Both work for me - under Linux with the curl and md5sum tools installed.
