### ISSUE TITLE
any Car tail lamp in night, is detected as "fire" in your model. How can I improve this ?

### ISSUE THREAD

**Issue by vimalpachiappan** [tobybreckon/fire-detection-cnn#53]
any Car tail lamp in night, is detected as "fire" in your model. How can I improve this ?
Images i have checked for example link : https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fsikandcar%2Fposts%2Fsuzuki-baleno-tail-lights%2F1427205764052962%2F&psig=AOvVaw0WgUWdxxJb3XQW2JBnB8oM&ust=1589542621204000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDG78-hs-kCFQAAAAAdAAAAABAi

**Comment by tobybreckon** [comment]
Which model are you referring to - we provide 8 of them ? 
Please provide details of platform/environment ... etc.

To check: you are loading this as BGR channel ordering, resizing to 224x224, pixel range 0 -> 255 as per PAQ  ?

As the paper(s) say it is 93-9x% accurate - not 100%. Please provide a link to a downloadable video example as these objects are in the -ve set.
