### ISSUE TITLE
Can' find Dunnings annotations

### ISSUE THREAD

**Issue by JoseLuisFriedrich** [tobybreckon/fire-detection-cnn#58]
I downloaded the Dunnings dataset, but all I see is images, don't see the labels.
Anyone knows where I can find those?

**Comment by tobybreckon** [comment]
As per the paper which accompanies the repository and dataset, this work tackles both binary full frame detection and superpixel based localisation.

There are no in-frame annotations for the dataset as all of the images are labelled on a per image basis globally as fire or no fire.

A subset of the data is the Steffens (check spelling, on phone) dataset for which XML annotations are available from the original source. See ref in paper.
