### ISSUE TITLE
pre-trained model not in .pb format ...

### ISSUE THREAD

**Issue by Bahramudin** [tobybreckon/fire-detection-cnn#6]
Error Output:

> Downloading pretrained models...
> ################################################################################################################ 100.0%
> checking the MD5 checksum for downloaded models...
> dunnings-2018-fire-detection-pretrained-models.zip: FAILED
> md5sum: WARNING: 1 computed checksum did NOT match

**Comment by tobybreckon** [comment]
I have just tested this from two hosts; one on-site here at Durham and off-site one elsewhere via ssh  ...

On OpenSUSE Leap 15, I get:

```
toby@HOSTNAME[/tmp/fire-detection-cnn] sh ./download-models.sh
Downloading pretrained models...
###################################################################################################### 100.0%
**checking the MD5 checksum for downloaded models...
dunnings-2018-fire-detection-pretrained-models.zip: OK**
Unpacking the zip file...
Tidying up...
... completed -> required models are in models/
toby@HOSTNAME[/tmp/fire-detection-cnn] date
Mon 18 Mar 09:21:12 GMT 2019
```

On Debian GNU/Linux 9 (stretch), I get:

```
toby@HOSTNAME:/tmp/fire-detection-cnn$ sh ./download-models.sh
Downloading pretrained models...
######################################################################## 100.0%
**checking the MD5 checksum for downloaded models...
dunnings-2018-fire-detection-pretrained-models.zip: OK**
Unpacking the zip file...
Tidying up...
... completed -> required models are in models/
toby@HOSTNAME:/tmp/fire-detection-cnn$ date
Mon 18 Mar 09:24:23 GMT 2019
```

- all appears well with the MD5 check. So either your download has failed and the MD5 check has correctly identified this (which is what it is supposed to do) or for some reason your system is different. 

Please can you send the output of the following commands:
```
uname -a
md5sum --version | head -1
```

The download is ~700Mb when unzipped - do you have enough disk space where you are downloading to ? / Does the download manually from the browser work ? (link is via [https://collections.durham.ac.uk/files/r19880vq98m#.XI9i5pzgqfY](https://collections.durham.ac.uk/files/r19880vq98m#.XI9i5pzgqfY))

Thanks, T.

**Comment by Bahramudin** [comment]
@tobybreckon Thanks for the reply! Yes, I have tried and it was working and already has downloaded. 
But inside models folder there now I have three more folders:

> FireNet
> InceptionV1-OnFire
> SP-InceptionV1-OnFire

But I did not find any **frozen_inference_graph.pb** graph file which I need to read this with OpenCV and forward the image to the network.

Now, what should I do how to convert the trained model into .pb format file?

I am going to use this in OpenCV using C++.

Thanks!

**Comment by tobybreckon** [comment]
The models are in tflearn checkpoint format unfortunately - I have started a separate branch of this repo [https://github.com/tobybreckon/fire-detection-cnn/tree/convert-pb](https://github.com/tobybreckon/fire-detection-cnn/tree/convert-pb) to try and provide a convertor from this format to protobuf format (pb). 

The workflow is recreate ``checkpoint`` file in path of current models (by re-running modified ``download-data.sh``  step, load model without training parts, re-save model, attempt to freeze model to .pb format, load into OpenCV DNN module as follows ...

```
$ git clone https://github.com/tobybreckon/fire-detection-cnn.git
$ cd fire-detection-cnn
$ git checkout convert-pb
$ sh ./download-models.sh
$ python pb-test.py 
```

... but one or both of the attempt to freeze model to .pb format or load into OpenCV DNN module is wrong as this **fails at the final loading stage** meaning the .pb format may be wrong in the earlier stage. I have run out of time on this presently - help needed. Please update and contribute to this branch with a possible fix.  

> I am going to use this in OpenCV using C++.

Beware, that at the current time - despite the fact OpenCV 3.x/4.x compiles with CUDA, the OpenCV DNN modules does not use the GPU - this feature is hopefully going to be added this summer as GSoC 2019 for OpenCV - [https://github.com/opencv/opencv/wiki/GSoC_2019](https://github.com/opencv/opencv/wiki/GSoC_2019). OpenCV and C++ will thus be slow unless you use the tensorflow/tflearn c++ api - see discussion [here](https://stackoverflow.com/questions/51357669/tensorflow-and-tflearn-c-api/51728099).

**Comment by tobybreckon** [comment]
Update - see also pb-test2.py file for a second attempt at this - still unsuccessful.

**Comment by Bahramudin** [comment]
@tobybreckon I think the better way that everyone can get the benefit of your effort is to convert the library to its binary format (.pb frozen graph) and also to be usable in OpenCV as well then convert to (.pbtxt) because some people don't know python, but C++ or Java, so if everything [converted](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) well, then it will belong to any specific language, and is ready to use it directly BUT not in a development environment.

If you do not do these steps, then very fewer people will be to get benefit from your effort.
For me, it was really impossible to run it, although I am a C++ and Java development language engineer.

Thanks!

**Comment by tobybreckon** [comment]
To use the current model format (checkpoint) with C++ just follow this example ... https://stackoverflow.com/questions/35508866/tensorflow-different-ways-to-export-and-run-graph-in-c/43639305#43639305

**Comment by Bahramudin** [comment]
@tobybreckon The below error occurs while running `pb-test.py,pb-test2.py`

> Traceback (most recent call last):
>   File "pb-test2.py", line 27, in <module>
>     import tflearn
> ModuleNotFoundError: No module named 'tflearn'

**Comment by tobybreckon** [comment]
You need to install the tflearn api interface to tensorflow ....
https://stackoverflow.com/questions/40880925/importerror-no-module-named-tflearn

Be-aware, we per earlier posts - ```pb-test.py,pb-test2.py``` do not work correctly (I know this, do not post to tell me this please) - my next steps are to visualize the output of the ```.pb``` files in tensorboard to make sure they are sensible against the models in the paper/diagrams and then investigate why these .pb files still do not load into opencv. If you can help with this, please go ahead and let me know your findings.

**Comment by tobybreckon** [comment]
@Bahramudin - this issue is fully resolved now and the models can be exported in tensorflow .pb format for use with the OpenCV DNN module using the new scripts provided (in OpenCV 4.1.0-pre or later from github - a change in the OpenCV source code was also required to make these models work).

See section **Instructions to use pre-trained models with other frameworks:**  at https://github.com/tobybreckon/fire-detection-cnn

Hope this helps you and others.
