### ISSUE TITLE
Saving Weights After Traning

### ISSUE THREAD

**Issue by dodo269696** [tobybreckon/fire-detection-cnn#7]
**Describe the issue**
< We are trying to improve your work -Firenet. We are training your pretrainied model with our own dataset which is containing fire smoke images. However we do not know with what extention should we save the new weights at the end of traning (in models folder there 3 files named differently but do not know which one is weights of Firenet. So rougly we are using pretrained model and want to improve it..  >.

**Computing Environment (please complete the following information):**
 - OS:Windows 10 (re- organised for windows from linux)

![2019-03-19 19_38_12-Window](https://user-images.githubusercontent.com/45074026/54624536-9a812380-4a7e-11e9-9e1e-1b3383a35991.png)
.

**Comment by tobybreckon** [comment]
Using the tflearn API you should be able just do to .... 

```
model.load(os.path.join("models/FireNet", "firenet"),weights_only=True)
.... < do your training here using our pretrained model as your initialization (see tflearn tutorials/api)
model.save("firenet-smokey")
```

... which will then produce three files firenet-smokey.* of the same types as above. As far as I am aware tflearn stores its models across all of these three files in this checkpoint format - for more info see the tflearn manual + docs.
